export const properties = [
    {
        id: 1,
        type: 'rent',
        title: 'Modern 2BHK Apartment',
        location: 'Koramangala',
        area: 'koramangala',
        price: 25000,
        priceType: 'month',
        description: 'Beautiful modern apartment with excellent amenities and great location.',
        beds: 2,
        baths: 2,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Fully Furnished', '24/7 Security', 'Parking Available', 'Near Metro Station']
    },
    {
        id: 2,
        type: 'pg',
        title: 'Premium PG for Working Professionals',
        location: 'Indiranagar',
        area: 'indiranagar',
        price: 12000,
        priceType: 'month',
        description: 'Comfortable PG accommodation with all modern facilities.',
        beds: 1,
        baths: 1,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['AC Rooms', '3 Meals Daily', 'Laundry Service', 'Study Room']
    },
    {
        id: 3,
        type: 'lease',
        title: 'Spacious 3BHK Villa',
        location: 'Jayanagar',
        area: 'jayanagar',
        price: 45000,
        priceType: 'month',
        description: 'Luxurious villa perfect for families with garden and parking.',
        beds: 3,
        baths: 3,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Private Garden', 'Car Parking', 'Servant Quarter', 'Power Backup']
    },
    {
        id: 4,
        type: 'coliving',
        title: 'Tech Startup Co-living Space',
        location: 'Whitefield',
        area: 'whitefield',
        price: 18000,
        priceType: 'month',
        description: 'Modern co-living space designed for tech professionals.',
        beds: 1,
        baths: 1,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['High-Speed Internet', 'Co-working Space', 'Gym Access', 'Events & Networking']
    },
    {
        id: 5,
        type: 'buy',
        title: 'Luxury 4BHK Penthouse',
        location: 'Koramangala',
        area: 'koramangala',
        price: 8500000,
        priceType: 'total',
        description: 'Stunning penthouse with panoramic city views and premium finishes.',
        beds: 4,
        baths: 4,
        wifi: false,
        image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Panoramic Views', 'Private Terrace', 'Premium Finishes', 'Smart Home Features']
    },
    {
        id: 6,
        type: 'rent',
        title: 'Cozy 1BHK Studio',
        location: 'Marathahalli',
        area: 'marathahalli',
        price: 15000,
        priceType: 'month',
        description: 'Perfect studio apartment for singles or couples.',
        beds: 1,
        baths: 1,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Modern Kitchen', 'Balcony', 'Pet Friendly', 'Close to IT Parks']
    },
    {
        id: 7,
        type: 'pg',
        title: 'Girls PG - Safe & Secure',
        location: 'Jayanagar',
        area: 'jayanagar',
        price: 10000,
        priceType: 'month',
        description: 'Exclusive PG for women with safety features and amenities.',
        beds: 1,
        baths: 1,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Women Only', 'CCTV Security', 'Homely Food', 'Transportation']
    },
    {
        id: 8,
        type: 'lease',
        title: 'Commercial Space for Lease',
        location: 'Indiranagar',
        area: 'indiranagar',
        price: 75000,
        priceType: 'month',
        description: 'Prime commercial location perfect for retail or office space.',
        beds: 0,
        baths: 2,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['High Footfall', 'Parking Space', 'Storage Area', 'Flexible Lease Terms']
    },
    {
        id: 9,
        type: 'coliving',
        title: 'Artists & Creatives Hub',
        location: 'Koramangala',
        area: 'koramangala',
        price: 22000,
        priceType: 'month',
        description: 'Creative co-living space with art studios and collaborative areas.',
        beds: 1,
        baths: 1,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Art Studios', 'Creative Community', 'Exhibition Space', 'Flexible Timings']
    },
    {
        id: 10,
        type: 'buy',
        title: 'Plot for Construction',
        location: 'Whitefield',
        area: 'whitefield',
        price: 2500000,
        priceType: 'total',
        description: '1200 sq ft plot in prime location ready for construction.',
        beds: 0,
        baths: 0,
        wifi: false,
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Clear Title', 'Corner Plot', 'Approved Layout', 'Near Schools']
    },
    {
        id: 11,
        type: 'rent',
        title: 'Executive 3BHK Apartment',
        location: 'Whitefield',
        area: 'whitefield',
        price: 35000,
        priceType: 'month',
        description: 'Executive apartment with luxury amenities and club facilities.',
        beds: 3,
        baths: 2,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Swimming Pool', 'Gym', 'Club House', 'Concierge Service']
    },
    {
        id: 12,
        type: 'pg',
        title: 'Budget PG for Students',
        location: 'Marathahalli',
        area: 'marathahalli',
        price: 8000,
        priceType: 'month',
        description: 'Affordable accommodation for students with essential amenities.',
        beds: 1,
        baths: 1,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Near Colleges', 'Basic Amenities', 'Shared Kitchen', 'Study Hours']
    },
    {
        id: 13,
        type: 'lease',
        title: 'Duplex House with Garden',
        location: 'Jayanagar',
        area: 'jayanagar',
        price: 55000,
        priceType: 'month',
        description: 'Beautiful duplex house with private garden and modern amenities.',
        beds: 4,
        baths: 3,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Private Garden', 'Duplex Design', 'Modular Kitchen', 'Children\'s Play Area']
    },
    {
        id: 14,
        type: 'coliving',
        title: 'Digital Nomad Co-living',
        location: 'Indiranagar',
        area: 'indiranagar',
        price: 25000,
        priceType: 'month',
        description: 'Designed for digital nomads with high-speed internet and co-working spaces.',
        beds: 1,
        baths: 1,
        wifi: true,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['1Gbps Internet', 'Co-working Desk', 'Global Community', 'Flexible Stay']
    },
    {
        id: 15,
        type: 'buy',
        title: 'Ready to Move 2BHK',
        location: 'Marathahalli',
        area: 'marathahalli',
        price: 4200000,
        priceType: 'total',
        description: 'Ready to move apartment in gated community with all amenities.',
        beds: 2,
        baths: 2,
        wifi: false,
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
        highlights: ['Gated Community', 'Ready to Move', 'Children\'s Park', 'Security']
    }
];
